apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongoapp
  labels:
    name:  mongoapp
spec:
  template:
    metadata:
      labels:
        name:  mongoapp
  selector: 
    matchLabels:
      name: mongoapp
    spec:
      containers:
      - image:  mongo
        name:  mongo

        env:
        - name:  MONGO_INITDB_ROOT_USERNAME
          value:  root     
        - name: MONGO_INITDB_ROOT_PASSWORD 
          value: password
        ports:
        - containerPort:  27017
       
      